INSERT INTO users (USERNAME, PASSWORD, ENABLED, FIRST_NAME)
VALUES ('user', '$2a$10$BRaNrwxklcU6t.i87r3wbugGHIQoBgkz9cM8dHm5SJEWwhUjROk3C', true, 'Jack');
INSERT INTO users (USERNAME, PASSWORD, ENABLED, FIRST_NAME)
VALUES ('admin', '$2a$10$EjkaDYMdT11QFAiIAwTuWelEXo2viLxlTOaLEswlhe9VyyMmmXpay', true, 'Jill');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('user', 'ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('admin', 'ROLE_ADMIN');
-- select 1;