-- insert into orders(ordernumber) values ('abc');
-- insert into orders(ordernumber) values ('123');
-- insert into orders(ordernumber) values ('ddd');
-- insert into orders(ordernumber) values ('ccc');
-- insert into orders(ordernumber) values ('fff');
-- insert into orders(ordernumber) values ('ggg');
-- insert into orders(ordernumber) values ('hhh');
--
--
-- insert into items(orderid, itemname, quantity, price)  values(1, 'asdasd', 2, 5);
-- insert into items(orderid, itemname, quantity, price)  values(1, 'sadasd', 2, 5);
select 1;